### ISSUE TITLE
No names of containers at the last test 

### ISSUE THREAD

**Issue by masterwishx** [SpaceinvaderOne/Unraid_check_docker_script#1]
Thanks for great script , but i dont have containers names in last test of script 
(List of docker volumes, the container which they are connected to their size) : 
Using Unraid 6.9.2
![image](https://user-images.githubusercontent.com/28630321/161913941-6e8f7dde-a8f5-44e1-9e72-0d766fd83ae7.png)

**Comment by Kydonakis** [comment]
Got the same logs when run the script. Several tens of non-connected volumes. I have no orphans or misconfigured containers. Any feedback? Shall those be removed?

##################################################################################
List of docker volumes, the container which they are connected to their size
##################################################################################

ID 0ac1866ead4dfebdad46e1bac609e620269b813058b182adf32c0c8f8261fa6d
This volume connected to has a size of 0

ID 0b002c62fff0c4645f722877d6aae1c16e23fc7bf2bb4a327d64e1c47cc68eb5
This volume connected to has a size of 0

ID 0b5a15cbcc8cf8293baae7c98e3c7422200b93e2a764fc55b53870dcb5d852fc
This volume connected to has a size of 0

ID 0b70c208384feb550e5f4607cc697edfc753b788768490cf747a622bfadc9371
This volume connected to has a size of 0

ID 0b73c7f35f3fb868bc131b1b8d2684de6487dad0866999aded958106bdd070b1
This volume connected to has a size of 0

ID 0bbd4ce1634d2f63b7e16ebdd51e582ee8ae5df7d7b4be1a622b5cd6dbd82d78
This volume connected to has a size of 0

ID 0c9c3491ca060713185d32ae43a0f93bc350d7aad13f8995a9f4240395892a7a
This volume connected to has a size of 0

**Comment by pellz0r** [comment]
I noticed this as well. So when the name is missing the volume is non-connected (and should be safe to remove)?

**Comment by masterwishx** [comment]
> I noticed this as well. So when the name is missing the volume is non-connected (and should be safe to remove)?

in my case all volume is connected and they all missing names ,
When i run "docker ps -a --format '{{.Names}}' | sed 's/^/  /'" in terminal i got all names ,so somethink 
with this line that not print names of containers .
i hope it will be checked and fixed by SpaceinvaderOne

**Comment by pellz0r** [comment]
> > I noticed this as well. So when the name is missing the volume is non-connected (and should be safe to remove)?
> 
> in my case all volume is connected and they all missing names , When i run "docker ps -a --format '{{.Names}}' | sed 's/^/ /'" in terminal i got all names ,so somethink with this line that not print names of containers . i hope it will be checked and fixed by SpaceinvaderOne

I think the issue is in the filter argument. 
name=`(docker ps -a --filter volume="$volume" --format '{{.Names}}' | sed 's/^/  /')`

If you look a few lines up, the $volume is set by:
volumes=$(docker volume ls  --format '{{.Name}}')

So if you run docker volume ls --format '{{.Name}}' that will list all the volumes.

Take one of the listed volumes, and insert it in the first command:
docker ps -a --filter volume=<volume from list>

The output will probably be empty.

**Comment by pellz0r** [comment]
I just ran the script with with remove orphaned and unconnected volumes set to yes. It removed all volumes that didn't show names. Re-ran the script again with remove set to no, and now only 3 volumes remained, and showing the name to the connected container.

An improvement to the script would be to clearly print that each volume that is missing the name is unconnected.

**Comment by masterwishx** [comment]
> I think the issue is in the filter argument.
> name=`(docker ps -a --filter volume="$volume" --format '{{.Names}}' | sed 's/^/ /')`

Yes

**Comment by pellz0r** [comment]
My coding skills is quite limited, but maybe a simple if statement might be sufficient?

```
if [ -z "$volume" ] ; then
    echo "This unconnected volume has a size of" $size
  else
    echo "This volume connected to" $name "has a size of" $size
  fi
```

**Comment by masterwishx** [comment]
> statement might be sufficient?

its more Bash script plus docker commands  , the author of script maybe will fix it if will have time .
if not i think anyone can try to make more advanced addons on it for himself.

in my case its not parsing the container names at all so IF will not help to my case i think and i dont know best way to fix it for now but founded something in google and if will have more time will check it ...

**Comment by masterwishx** [comment]
After some more checking i founded the script is working after i runned "docker volume prune -f" like in script and its deleted a lot of volumes 1.2G that not connected and now it show 11 volumes with names.

So the script is fully working after you set Yes to remove any orphaned images  ,remove_unconnected_volumes.

Also big Thanks for SpaceinvaderOne for his work , i  learned a lot  in unraid and linux on his coolest videos.

**Comment by masterwishx** [comment]
> if [ -z "$volume" ] ; then
>     echo "This unconnected volume has a size of" $size
>   else
>     echo "This volume connected to" $name "has a size of" $size
>   fi

i think you meaned "$name"

**Comment by pellz0r** [comment]
> > if [ -z "$volume" ] ; then
> > echo "This unconnected volume has a size of" $size
> > else
> > echo "This volume connected to" $name "has a size of" $size
> > fi
> 
> i think you meaned "$name"

I guess either works... if $volume is empty $name will be empty too.

**Comment by masterwishx** [comment]
name= container name
But volume= hash of volume
So I added ( if $name... ) and its working, shows name for connected and unconnected.

**Comment by pellz0r** [comment]
> name= container name But volume= hash of volume So I added ( if $name... ) and its working, shows name for connected and unconnected.

I think you mix $volumes with $volume.
$volumes is the list of docker volumes
$volume is defined in the for loop using the list from $volumes.

But as previously said, both should work :)

**Comment by pellz0r** [comment]
Sorry, it's me who can't read... You're totally right. $volume/$volumes is the volume hash. if $name is the proper way, case closed :D
